const style = theme => ({
  section: {
    padding: '100px 72px',
    backgroundColor: '#0a0e1a',
    [theme.breakpoints.down('md')]: { padding: '80px 24px' },
  },
  inner: {
    maxWidth: 640,
    margin: '0 auto',
    textAlign: 'center',
  },
  sectionLabel: {
    fontFamily: '"Fira Code", monospace',
    fontSize: 12,
    color: '#4f8ef7',
    display: 'block',
    marginBottom: 10,
    letterSpacing: '0.04em',
  },
  sectionTitle: {
    fontSize: 'clamp(34px, 4vw, 52px)',
    fontWeight: 800,
    color: '#f1f5f9',
    letterSpacing: '-1.5px',
    lineHeight: 1.05,
    marginBottom: 16,
  },
  sub: {
    fontSize: 15,
    color: '#4b5977',
    lineHeight: 1.8,
    maxWidth: 480,
    margin: '0 auto 48px',
  },
  emailLink: {
    display: 'inline-block',
    fontSize: 'clamp(18px, 3vw, 30px)',
    fontWeight: 700,
    color: '#f1f5f9',
    textDecoration: 'none',
    letterSpacing: '-0.5px',
    position: 'relative',
    marginBottom: 56,
    transition: 'color 0.2s',
    '&::after': {
      content: '""',
      position: 'absolute',
      bottom: -4, left: 0, right: 0,
      height: 2,
      background: '#4f8ef7',
      transform: 'scaleX(0)',
      transformOrigin: 'left',
      transition: 'transform 0.3s ease',
    },
    '&:hover': { color: '#4f8ef7' },
    '&:hover::after': { transform: 'scaleX(1)' },
  },
  socials: {
    display: 'flex',
    justifyContent: 'center',
    gap: 12,
    flexWrap: 'wrap',
  },
  socialPill: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '10px 22px',
    border: '1px solid rgba(255,255,255,0.07)',
    borderRadius: 8,
    color: '#4b5977',
    textDecoration: 'none',
    fontSize: 13,
    fontWeight: 500,
    transition: 'border-color 0.2s, color 0.2s, background 0.2s',
    '& svg': { width: 15, height: 15, flexShrink: 0 },
    '&:hover': {
      borderColor: 'rgba(79,142,247,0.35)',
      color: '#f1f5f9',
      background: 'rgba(79,142,247,0.05)',
    },
  },
});

export default style;
